name: app
description: "Social Task"
version: 1.5.0+20

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  marquee: ^2.3.0
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.5
  flutter_inappwebview: ^6.1.5
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  firebase_remote_config: ^5.4.5
  share_plus: ^7.0.0
  app_links: ^3.0.0
  android_play_install_referrer: ^0.4.0
  intl: ^0.20.2
  in_app_update: ^4.1.1
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  in_app_purchase: ^3.2.3
  rate_my_app: ^2.3.2
  flutter_overlay_window: ^0.5.0
  android_intent_plus: ^5.0.2
  unity_ads_plugin: ^0.3.28




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#08456C"
  adaptive_icon_foreground: assets/images/socialtask.png

flutter_native_splash:
  color: "#014665"
  image: assets/images/socialtask.png
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/ico/
    - assets/animations/

  # example:
  fonts:
    - family: WelcomeFont
      fonts:
        - asset: assets/fonts/Bokor-Regular.ttf
    - family: BoostAudience
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: 3rdRoboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
